### PR TITLE
Changing to use SERVER_NAME to ignore ports

### PR DESCRIPTION
**Pull request by catharsisjelly**
I was hoping to also include tests but I have not been developing for Silverstripe long and not entirely sure how to go about doing that as yet.

### CODE REVIEW

**Comment by dhensby** [comment]
So the problem is that `$_SERVER['HTTP_HOST']` contains the port number if that's included in the URL?

Using `$_SERVER['SERVER_NAME']` will have some very unintended side-effects, I believe. The servername may well stay the same across vhosts defined on a server. I think it'd be better to just pull the port number off the host. eg:

```php
$currentHost = $_SERVER['HTTP_HOST'];
if (strpos(':', $currentHost) !== false) {
list($currentHost, $currentPort) = explode(':', $currentHost, 2);
```

**Comment by catharsisjelly** [comment]
@dhensby I'd be okay with that as a solution I'll make the relevant change to my PR

**Comment by tractorcow** [comment]
If you want sites to differ by port only e.g. `localhost:8080` and `localhost:9090` then you'll need to include the port in the domain comparison.

If you DON'T want to allow port-only distinction, then this change is ok as-is.

I suggest documenting this depending on the direction chosen.

**Comment by dhensby** [comment]
I don't think port distinction falls in the remit of "multi-domain"

**Comment by catharsisjelly** [comment]
Thanks @dhensby

**Pull request merged**
