### PR TITLE
SS4 compat: Namespacing, PSR-4 autoloading, composer require bump, add upgrade mapping

### PR DESCRIPTION
**Pull request by robbieaverill**
## Requirements

- Branch current master off for legacy support (maybe release a current version tag?)
- Update composer branch alias?

This PR adds:

- Namespaces
- PSR-4 autoloading
- Updated Travis and composer configuration, and readme

### CODE REVIEW

**Comment by dhensby** [comment]
oh damn - current master has no alias and there are no releases... everyone's going to be on `dev-master` :(

**Comment by dhensby** [comment]
OK - I've tagged 1.0.0, and I've branched 1.0. feel free to do what you need in master

**Comment by robbieaverill** [comment]
New branch for SS4 then? Maybe `2`?

**Comment by robbieaverill** [comment]
Ok

**Comment by dhensby** [comment]
Please add the 2.0.x-dev alias to the composer.json

**Pull request merged**
